site_name: My Knowledge DB - BigD
repo_url: https://github.com/Hardcode3/BigD.git
repo_name: Hardcode3/BigD
site_author: Baptiste PENOT
copyright: © 2024 Baptiste Penot. All rights reserved.
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
theme:
  name: material
  logo: res/main_icon.png
  font:
    text: Ubuntu
    code: Roboto mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
plugins:
  - search
  - bibtex:
      bib_file: docs/refs.bib
markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown_include.include:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Contact:
      - contact.md
  - Dev:
      - dev/cyber_security.md
      - dev/code_quality.md
      - AI:
          - dev/ai/generative_ai.md
      - API:
          - dev/api/api.md
          - dev/api/rest_api.md
          - dev/api/api_testing.md
      - Cloud Services:
          - dev/cloud_services/cloud_services_comparison.md
          - dev/cloud_services/aws/aws.md
      - Computer Science:
          - dev/computer_science/parallelism_and_concurrency.md
          - dev/computer_science/program_process_thread.md
          - dev/computer_science/url_uri_urn.md
          - dev/computer_science/multithreading.md
      - Database:
          - dev/database/relational_database.md
      - Languages:
          - Python:
              - dev/languages/python/about_init_files.md
              - dev/languages/python/wheels.md
              - dev/languages/python/environments.md
          - Bash:
              - dev/languages/bash/bash_basics.md
              - Scripts examples:
                  - dev/languages/bash/scripts/confgure_and_build_cmake_solution.md
                  - dev/languages/bash/scripts/delete_folder.md
                  - dev/languages/bash/scripts/configure_python_environment.md
                  - dev/languages/bash/scripts/run_doxygen.md
          - CXX:
              - dev/languages/cpp/cppcon_2022_back_to_basics_cpp_api_design.md
              - dev/languages/cpp/pybind11_basics.md
          - Java:
              - dev/languages/java/java_basics.md
          - Markdown:
              - dev/languages/markdown/markdown_basics.md
          - SQL:
              - dev/languages/sql/sql.md
              - dev/languages/sql/sql_examples.md
      - Software architecture:
          - dev/software_architecture/design_patterns.md
          - dev/software_architecture/software_architecture.md
          - dev/software_architecture/unified_modelling_language.md
          - dev/software_architecture/authentication_mechanisms.md
      - Dev Sec Ops:
          - dev/devsecops/software_version_numbers.md
          - dev/devsecops/software_development_lifecycle.md
      - Tools:
          - dev/tools/curl.md
          - dev/tools/brew.md
          - dev/tools/git.md
          - dev/tools/screen.md
          - dev/tools/tar.md
          - dev/tools/vcpkg.md
          - dev/tools/docker.md
          - dev/tools/docker-compose.md
          - dev/tools/portainer.md
          - dev/tools/github.md
          - dev/tools/amazon_aws.md
          - dev/tools/virtualization.md
      - IDE:
          - dev/ide/vscode.md
      - Operating Systems:
          - dev/os/linux_file_system.md
  - Algorithms:
      - algorithms/simulated_annealing.md
      - algorithms/rejection_sampling.md
      - algorithms/metropolis_hastings.md
      - algorithms/markov_chain_monte_carlo.md
      - algorithms/inverse_problem_theory.md
      - algorithms/algorithm_glossary.md
      - algorithms/numerical_optimization.md
      - algorithms/big_0_notation.md
  - Data Structures:
      - data_structures/data_structures.md
      - data_structures/digit_representations.md
      - data_structures/meshes.md
      - data_structures/quadtree.md
      - data_structures/spatial_acceleration_structures.md
  - File Formats:
      - file_formats/json.md
      - file_formats/obj.md
      - file_formats/segy.md
      - file_formats/xml.md
  - Geoscience:
      - Seismic:
          - geoscience/seismic/eikonal_equation.md
          - geoscience/seismic/seismic_industry_history.md
          - geoscience/seismic/fast_marching_method.md
          - geoscience/seismic/fast_sweeping_method.md
          - geoscience/seismic/full_waveform_inversion.md
          - geoscience/seismic/born_modelling.md
          - geoscience/seismic/tomography.md
          - geoscience/seismic/seismic_fundamentals.md
  - Physics:
      - physics/huygens_principle.md
      - physics/wave_propagation.md
  - Mathematics:
      - Signal Processing:
          - mathematics/fourrier_transform.md
          - mathematics/sampling_theory.md
