site_name: Documentation
repo_url: https://github.com/Hardcode3/mkdocs_template
repo_name: Hardcode3/mkdocs_template
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
  logo: res/main_icon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    #- navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search


markdown_extensions:
    - def_list
    - pymdownx.highlight
    - pymdownx.superfences
    - attr_list
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - markdown_include.include:
        base_path: docs
    - pymdownx.tabbed:
        alternate_style: true
    - abbr
    - attr_list
    - pymdownx.snippets
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - Home: index.md
    - Computer Science:
      - computer_science\digit_representations.md
      - Algorithms:
        - computer_science\algorithms\simulated_annealing.md
      - Languages:
        - Python:
          - computer_science/languages/python/about_init_files.md
          - computer_science/languages/python/wheels.md
          - computer_science\languages\python\environments.md
        - Bash:
          - computer_science\languages\bash\bash_basics.md
          - Scripts examples:
            - computer_science\languages\bash\scripts\confgure_and_build_cmake_solution.md
            - computer_science\languages\bash\scripts\delete_folder.md
            - computer_science\languages\bash\scripts\configure_python_environment.md
            - computer_science\languages\bash\scripts\run_doxygen.md
        - CXX:
          - computer_science\languages\cpp\cppcon_2022_back_to_basics_cpp_api_design.md
          - computer_science\languages\cpp\pybind11_basics.md
        - Java:
          - computer_science\languages\java\java_basics.md
        - Markdown:
          - computer_science\languages\markdown\markdown_basics.md
        - SQL:
          - computer_science\languages\sql\sql_examples.md
      - Software architecture:
        - computer_science\software_architecture\design_patterns.md
        - computer_science\software_architecture\software_architecture.md
        - computer_science\software_architecture\unified_modelling_language.md
      - Tools:
        - computer_science\tools\brew.md
        - computer_science\tools\git.md
        - computer_science\tools\screen.md
        - computer_science\tools\tar.md
        - computer_science\tools\vcpkg.md
